{
  description = "Aalborg supercomputer klub nix flake";
  nixConfig = {
    extra-substituters = ["https://aalborg-supercomputer-klubben.cachix.org"];
    extra-trusted-public-keys = ["aalborg-supercomputer-klubben.cachix.org-1:4n8Usz0B/8hepttQS03DxknN+nP0ab48nhsx/CEVaz0="];
  };

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-25.11";
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    hercules-ci-effects = {
      url = "github:hercules-ci/hercules-ci-effects";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    sops-nix,
    hercules-ci-effects,
  }: let
    system = "x86_64-linux";
    pkgs = import nixpkgs {inherit system;};
    keys = import ./keys.nix;

    # Common modules shared by all machines.
    commonModules = [
      sops-nix.nixosModules.sops
      ./common.nix
      ./sops.nix
    ];

    # Shell script that generates .sops.yaml from keys.nix using ssh-to-age.
    sops-gen-config = pkgs.writeShellApplication {
      name = "sops-gen-config";
      runtimeInputs = with pkgs; [ssh-to-age jq nix];
      text = ''
        REPO_ROOT="''${1:-.}"
        SOPS_FILE="$REPO_ROOT/.sops.yaml"

        echo "Generating $SOPS_FILE from keys.nix..."

        keys_json=$(nix eval --impure --json --expr '(import ./keys.nix)')

        {
          echo "# Auto-generated by: nix run .#sops-gen-config"
          echo "# Do not edit manually. Re-run the command after modifying keys.nix."
          echo "keys:"

          # Process user ed25519 keys, appending _N suffix when a user has multiple keys
          echo "$keys_json" | jq -r '.users | to_entries[] | .key as $name | [.value[] | select(startswith("ssh-ed25519"))] | length as $count | to_entries[] | "\($name) \(.key + 1) \($count) \(.value)"' |
          while read -r name idx count sshkey; do
            age_key=$(echo "$sshkey" | ssh-to-age 2>/dev/null) || continue
            if [ "$count" -gt 1 ]; then
              anchor="''${name}_''${idx}"
            else
              anchor="$name"
            fi
            echo "  - &$anchor $age_key"
          done

          # Process server ed25519 keys
          echo "$keys_json" | jq -r '.servers | to_entries[] | select(.value | startswith("ssh-ed25519")) | "\(.key) \(.value)"' |
          while read -r name sshkey; do
            age_key=$(echo "$sshkey" | ssh-to-age 2>/dev/null) || continue
            echo "  - &$name $age_key"
          done

          echo "creation_rules:"
          echo "  - path_regex: .*\\.sops\\.yaml$"
          echo "    key_groups:"
          echo "      - age:"

          # Add user anchors
          echo "$keys_json" | jq -r '.users | to_entries[] | .key as $name | [.value[] | select(startswith("ssh-ed25519"))] | length as $count | to_entries[] | if $count > 1 then "\($name)_\(.key + 1)" else $name end' |
          while read -r anchor; do
            echo "          - *$anchor"
          done

          # Add server anchors
          echo "$keys_json" | jq -r '.servers | to_entries[] | select(.value | startswith("ssh-ed25519")) | .key' |
          while read -r name; do
            echo "          - *$name"
          done
        } > "$SOPS_FILE"

        echo "Written $SOPS_FILE"
      '';
    };

    # Helper script for first-time setup: derives an age private key from your SSH key.
    sops-first-run = pkgs.writeShellApplication {
      name = "sops-first-run";
      runtimeInputs = with pkgs; [ssh-to-age];
      text = ''
        SSH_KEY="''${1:-$HOME/.ssh/id_ed25519}"

        if [ ! -f "$SSH_KEY" ]; then
          echo "Error: SSH key not found at $SSH_KEY"
          echo "Usage: nix run .#sops-first-run [path-to-ed25519-private-key]"
          exit 1
        fi

        AGE_FILE="''${SOPS_AGE_KEY_FILE:-$HOME/.config/sops/age/keys.txt}"
        AGE_DIR="$(dirname "$AGE_FILE")"

        mkdir -p "$AGE_DIR"

        NEW_KEY=$(ssh-to-age -private-key -i "$SSH_KEY")

        if [ -f "$AGE_FILE" ] && grep -qF "$NEW_KEY" "$AGE_FILE"; then
          echo "Key already present in $AGE_FILE, skipping."
        else
          echo "$NEW_KEY" >> "$AGE_FILE"
          chmod 600 "$AGE_FILE"
          echo "Age private key appended to $AGE_FILE"
        fi
        echo "Your age public key:"
        ssh-to-age -i "''${SSH_KEY}.pub"
      '';
    };
    hci-effects = hercules-ci-effects.lib.withPkgs pkgs;
    runCachixDeploy = hci-effects.runCachixDeploy;
  in rec {
    nixosConfigurations = {
      bacci = nixpkgs.lib.nixosSystem {
        inherit system;
        modules =
          commonModules
          ++ [
            ./common/hercules-ci.nix
            ./common/cachix-deploy-agent.nix
            ./servers/bacci
          ];
      };
      montoya = nixpkgs.lib.nixosSystem {
        inherit system;
        modules =
          commonModules
          ++ [
            ./common/hercules-ci.nix
            ./common/cachix-deploy-agent.nix
            ./servers/montoya
          ];
      };
      normark = nixpkgs.lib.nixosSystem {
        inherit system;
        modules =
          commonModules
          ++ [
            ./common/hercules-ci.nix
            ./common/cachix-deploy-agent.nix
            ./servers/normark
          ];
      };
      huttel = nixpkgs.lib.nixosSystem {
        inherit system;
        modules =
          commonModules
          ++ [
            ./common/hercules-ci.nix
            ./common/cachix-deploy-agent.nix
            ./servers/huttel
          ];
      };
      sbcc-router = nixpkgs.lib.nixosSystem {
        system = "aarch64-linux";
        modules =
          commonModules
          ++ [
            ./servers/sbcc-router
          ];
      };
    };
    packages.${system} = {
      inherit sops-gen-config sops-first-run;
    };
    apps.${system} = {
      sops-gen-config = {
        type = "app";
        program = "${sops-gen-config}/bin/sops-gen-config";
      };
      sops-first-run = {
        type = "app";
        program = "${sops-first-run}/bin/sops-first-run";
      };
    };
    herculesCI.onPush.default.outputs.effects.cachix-deploy = runCachixDeploy {
      async = true;
      deploy.agents = {
        bacci = nixosConfigurations.bacci.config.system.build.toplevel;
        montoya = nixosConfigurations.montoya.config.system.build.toplevel;
        normark = nixosConfigurations.normark.config.system.build.toplevel;
        huttel = nixosConfigurations.huttel.config.system.build.toplevel;
      };
    };
  };
}
