name: "Build configurations"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build fastboy
      run: nix build .#fastboy-vm
    - name: Build oldboy
      run: nix build .#oldboy-vm
